server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JIDUPINGFANREN/microservicecloud_config.git #GitHub上面的git仓库名字，3344默认访问此地址
 

